# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

games = Game.create!([
  { name: 'Kingdom Hearts HD 1.5 ReMIX', cover: 'kh1.5.jpg', rating: 0, summary: 'Kingdom Hearts HD 1.5 ReMIX is a compilation of the first two games plus a movie in the KINGDOM HEARTS experience remastered.', genre: 'Action role-playing game' }, 
  { name: 'Kingdom Hearts HD 2.5 ReMIX', cover: 'kh2.5.jpg', rating: 0, summary: 'Kingdom Hearts HD 2.5 ReMIX is a compilation of the next two games plus a movie in the KINGDOM HEARTS experience remastered.', genre: 'Action role-playing game' }, 
  { name: 'Kingdom Hearts HD 2.8 Final Chapter Prologue', cover: 'kh2.8.jpg', rating: 0, summary: 'Kingdom Hearts HD 2.8 Final Chapter Prologue is a compilation of two more games and a movie in the KINGDOM HEARTS experience remastered.', genre: 'Action role-playing game' }, 
  { name: 'Kingdom Hearts 3', cover: 'kh3.jpg', rating: 0, summary: 'Kingdom Hearts III is a 2019 action role-playing game developed and published by Square Enix for the PlayStation 4 and Xbox One. It is the twelfth installment in the Kingdom Hearts series, and serves as a conclusion of the "Dark Seeker Saga" story arc that began with the original game.', genre: 'Action role-playing game' }, 
  { name: 'Final Fantasy VII', cover: 'ff7.jpg', rating: 0, summary: "Final Fantasy VII is a 1997 role-playing video game developed by Square for the PlayStation console. It is the seventh main installment in the Final Fantasy series. Published in Japan by Square, it was released in other regions by Sony Computer Entertainment and is the first in the main series with a PAL release. The game's story follows Cloud Strife, a mercenary who joins an eco-terrorist organization to stop a world-controlling megacorporation from using the planet's life essence as an energy source. Events send Cloud and his allies in pursuit of Sephiroth, a former member of the organization who seeks to harm the planet. During the journey, Cloud builds close friendships with his party members, including Aerith Gainsborough, who holds the secret to saving their world.", genre: 'Role-playing game' }, 
  { name: 'Final Fantasy VII Remake', cover: 'ff7r.jpg', rating: 0, summary: "Final Fantasy VII Remake is a 2020 action role-playing game developed and published by Square Enix. It is the first in a planned series of games remaking the 1997 PlayStation game Final Fantasy VII. Set in the dystopian cyberpunk metropolis of Midgar, it puts players in the role of a mercenary named Cloud Strife. He joins AVALANCHE, an eco-terrorist group trying to stop the powerful megacorporation Shinra from using the planet's life essence as an energy source. The gameplay combines real-time action with strategic and role-playing elements.", genre: 'Action role-playing game' } 
])